language: python

python:
- '3.9'

install:
- pip install -r requirements.txt

addons:
  sonarcloud: true

script:
- sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jowi20
  -Dsonar.login=$SONAR_TOKEN -X
- pytest

notifications:
  slack: entornodeinte-7kl4185:GsBAv7KUh6sobdyEqsTKU6Xq


deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 5d8ebdf13622eb3510188e7cd5cbc6ad8119e25d
  app: myapp
  on:
    repo: Jowi20/Entorno3
